### PR TITLE
Templates API + Subaccounts API support + Ping()

### PR DESCRIPTION
**Pull request by kakysha**
@keighl don't stop me now :) implemented some subaccounts api calls and tested it. I see you're willing to keep your package simple, thus you can freely drop this PR, I won't be upset, as my additions were required in my work, don't sure that someone will ever be needed it.

### CODE REVIEW

**Comment by natebrennand** [comment]
+1 for adding support for Ping

**Comment by MarkSonghurst** [comment]
+1 for ping

**Comment by dstroot** [comment]
+1 - like to see this get merged.

**Comment by narup** [comment]
@keighl are you not planning to merge this?

**Comment by keighl** [comment]
Went for simple ping addition from #16

**Pull request closed without merging**
