### PR TITLE
Faster ci

### PR DESCRIPTION
**Pull request by c2h5oh**
Using containers makes small test suites like this one run way faster.
Also added testing against current stable version of Go in addition to tip.

### CODE REVIEW

**Comment by keighl** [comment]
wow, good call.

**Comment by jonopray** [comment]
The non-string merge vars change is broken for me. When I switch away from interface{} back to a string to string map it works correctly.

**Comment by c2h5oh** [comment]
@prismatica I'll do some extra testing in the morning - some details about what you mean by 'broken' would be nice.

**Comment by jonopray** [comment]
`ConvertMapToVariables(map[string]string{"key": "value"})` returns nil for me

**Comment by c2h5oh** [comment]
Thanks for the example. I'll be adding some unit tests to replicate the issue shortly. Expect something in the next couple of hours.

**Comment by keighl** [comment]
Hey @c2h5oh we fixed this over in #7

**Comment by c2h5oh** [comment]
Damn, you beat me to it - I've just wrapped stuff and pulled master only to notice new commits :+1:

**Pull request merged**
