### PR TITLE
Add support for non-string merge vars

### PR DESCRIPTION
**Pull request by c2h5oh**
Since introduction of handlebars support allowing types other than stings is really usefull

### CODE REVIEW

**Comment by keighl** [comment]
Great! Would you mind updating the tests? (a few `map[string]string` in there). And then I'll merge it right in. 

Thanks for the contribution!

**Comment by c2h5oh** [comment]
On it.

**Comment by c2h5oh** [comment]
DONE. Also travis was painfully slow on this one, so expect another pull request in another minute or so.

**Comment by keighl** [comment]
than you, sir!

**Pull request merged**
